### ISSUE TITLE
create shell can't select executable file

### ISSUE THREAD

**Issue by yanglimingcn** [jamesnvc/helm-switch-shell#1]
when create shell, I want to select /bin/bash not /bin/zsh. I can't  select it.
But when using origin function M-x shell, then I can choose shell file

**Comment by jamesnvc** [comment]
Interesting; `helm-switch-shell` just calls `shell`, so it should act essentially the same. I will take a look 👍

**Comment by jamesnvc** [comment]
Just pushed 265d982 which adds an action to let you choose the shell program when creating a new shell. Please let me know if there are any issues with this!
