### ISSUE TITLE
can not find shell

### ISSUE THREAD

**Issue by yanglimingcn** [jamesnvc/helm-switch-shell#2]
I have shell buffer
![image](https://user-images.githubusercontent.com/7091130/90296313-b2e8ae00-debd-11ea-9546-3cc7e0adc352.png)
but helm-switch-shell can not found it
![image](https://user-images.githubusercontent.com/7091130/90296348-c7c54180-debd-11ea-892d-86cb4f3b6c14.png)

I use Emacs27 in macos

**Comment by jamesnvc** [comment]
Ah, thanks for the bug report! I will push a fix shortly to make that work.

The long story is that this package was originally called `helm-switch-eshell` and was specifically for eshell; the name was changed to `helm-switch-shell` when support for term was added. I just added support for vterm yesterday, so adding shell-mode support will be no problem.

**Comment by jamesnvc** [comment]
Ah, thanks for the bug report! I will push a fix shortly to make that work.

It looks like a change yesterday to add support for `vterm` made a mistake.
