### ISSUE TITLE
use title for shell-switcher

### ISSUE THREAD

**Issue by yanglimingcn** [jamesnvc/helm-switch-shell#3]
hi, helm-switch-shell is useful and thanks for you job

can this swither use "shell title" to query?

It use path now
![image](https://user-images.githubusercontent.com/7091130/90353371-99d82c80-e078-11ea-9e77-dd9cd309d785.png)

**Comment by yanglimingcn** [comment]
i think use buffername is better, because when I use shell login to another machine i can also distinguish.

**Comment by jamesnvc** [comment]
Thank you, I'm very glad to hear you find it useful!

I will have a look at adding shell title to the query - I initially made it to just use directory, since I found myself with a bunch of buffers named `*eshell*`, `*eshell<1>*`, etc and directory was the only way to distinguish them, but as you say, title is useful for remote machines as well.

**Comment by jamesnvc** [comment]
It looks like getting the actual shell title directly may not be very straight-forward in general, but I'll have a look at display the buffer name, since hopefully the various shell packages have their own way of making the buffer name correspond to the terminal title.

**Comment by jamesnvc** [comment]
Just pushed 9cab3df, which also shows the buffer name in the switcher. For `emacs-libvterm`, one can customize the `vterm-buffer-name-string` variable to, e.g. `"vterm %s"`, which will make the buffer name show the path, including the remote host.

Please let me know if this works for you; for `shell` and `eshell` presumably will need some other configuration to show the host in the buffer name as well.

**Comment by yanglimingcn** [comment]
yes this works, buffername is unique in emacs, so it is reasonable. maybe you can change buffername and directory position, it will identical to ibuffer.

**Comment by yanglimingcn** [comment]
![image](https://user-images.githubusercontent.com/7091130/90594416-ee1c1180-e21c-11ea-968a-51cdb550cfd6.png)
buffers

**Comment by yanglimingcn** [comment]
buffer show like this
![image](https://user-images.githubusercontent.com/7091130/90594539-3fc49c00-e21d-11ea-8307-b134cca2855d.png)

**Comment by jamesnvc** [comment]
Ah, good call. I will push an update this weekend, hopefully.

**Comment by jamesnvc** [comment]
Pushed a few changes, let me know how that works for you!

**Comment by yanglimingcn** [comment]
yes fine, good job!
